-- Stop the permission denied errors please!
GRANT ALL ON ALL TABLES IN SCHEMA vrn TO inspire;
GRANT ALL ON ALL SEQUENCES IN SCHEMA vrn TO inspire;

GRANT ALL ON ALL TABLES IN SCHEMA bron TO inspire;
GRANT ALL ON ALL SEQUENCES IN SCHEMA bron TO inspire;

GRANT ALL ON ALL TABLES IN SCHEMA metadata TO inspire;
GRANT ALL ON ALL SEQUENCES IN SCHEMA metadata TO inspire;

GRANT ALL ON ALL TABLES IN SCHEMA public TO inspire;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO inspire;

GRANT ALL ON ALL TABLES IN SCHEMA manager TO inspire;
GRANT ALL ON ALL SEQUENCES IN SCHEMA manager TO inspire;

GRANT ALL ON ALL TABLES IN SCHEMA inspire TO inspire;
GRANT ALL ON ALL SEQUENCES IN SCHEMA inspire TO inspire;
